# Generated by Django 4.2 on 2023-05-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilustrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(help_text='Zadej jméno ilustrátora', max_length=50, unique=True, verbose_name='Jméno ilustrátora')),
                ('prijmeni', models.CharField(help_text='Zadej příjmení ilustrátora', max_length=50, unique=True, verbose_name='Příjmení ilustrátora')),
                ('zivotopis', models.TextField(blank=True, null=True)),
                ('datum_narozeni', models.DateTimeField(blank=True, null=True, verbose_name='Datum narození')),
            ],
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
