# Generated by Django 4.2 on 2023-05-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_ilustrator_delete_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilustrator',
            name='datum_narozeni',
        ),
        migrations.RemoveField(
            model_name='ilustrator',
            name='prijmeni',
        ),
        migrations.RemoveField(
            model_name='ilustrator',
            name='zivotopis',
        ),
    ]
