# Generated by Django 4.2 on 2023-05-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_remove_ilustrator_datum_narozeni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilustrator',
            name='datum_narozeni',
            field=models.DateField(blank=True, null=True, verbose_name='Datum narození'),
        ),
        migrations.AddField(
            model_name='ilustrator',
            name='prijmeni',
            field=models.CharField(help_text='Zadej příjmení ilustrátora', max_length=50, null=True, verbose_name='Příjmení ilustrátora'),
        ),
        migrations.AddField(
            model_name='ilustrator',
            name='zivotopis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ilustrator',
            name='jmeno',
            field=models.CharField(help_text='Zadej jméno ilustrátora', max_length=50, verbose_name='Jméno ilustrátora'),
        ),
    ]
