# Generated by Django 4.2 on 2023-05-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_ilustrator_datum_narozeni_ilustrator_prijmeni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(help_text='Zadej jméno autora', max_length=20, verbose_name='Jméno autora')),
                ('prijmeni', models.CharField(help_text='Zadej příjmení autora', max_length=50, null=True, verbose_name='Příjmení autora')),
                ('zivotopis', models.TextField(blank=True, null=True)),
                ('datum_narozeni', models.DateField(blank=True, null=True, verbose_name='Datum narození autora')),
                ('foto', models.ImageField(blank=True, help_text='Nahrejte fotku autora', null=True, upload_to='autori', verbose_name='Fotka autora')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autoři',
                'ordering': ['prijmeni'],
            },
        ),
        migrations.AlterModelOptions(
            name='ilustrator',
            options={'ordering': ['prijmeni'], 'verbose_name': 'Ilustrátor', 'verbose_name_plural': 'Ilustrátoři'},
        ),
        migrations.AddField(
            model_name='ilustrator',
            name='foto',
            field=models.ImageField(blank=True, help_text='Nahrejte fotku ilustrátora', null=True, upload_to='ilustratori', verbose_name='Fotka ilustrátora'),
        ),
        migrations.AlterField(
            model_name='ilustrator',
            name='datum_narozeni',
            field=models.DateField(blank=True, null=True, verbose_name='Datum narození ilustrátora'),
        ),
        migrations.AlterField(
            model_name='ilustrator',
            name='jmeno',
            field=models.CharField(help_text='Zadej jméno ilustrátora', max_length=20, verbose_name='Jméno ilustrátora'),
        ),
    ]
