# Generated by Django 4.2 on 2023-05-12 14:45

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_knizni_predloha_remove_ilustrator_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knizni_predloha',
            name='hodnoceni',
            field=models.CharField(help_text='Zadej průměrné hodnocení', max_length=2, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Průměrné hodnocení'),
        ),
        migrations.AlterField(
            model_name='knizni_predloha',
            name='rok_vydani',
            field=models.IntegerField(help_text='Zadej rok vydání knižní předlohy', verbose_name='Rok vydání'),
        ),
        migrations.AlterField(
            model_name='knizni_predloha',
            name='titul',
            field=models.CharField(help_text='Zadej název knižní předlohy', max_length=50, verbose_name='Název'),
        ),
    ]
