# Generated by Django 4.2 on 2023-05-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_alter_knizni_predloha_hodnoceni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titul', models.CharField(help_text='Zadej název anime', max_length=100, verbose_name='Název')),
                ('zanr', models.CharField(choices=[('fantasy', 'Fantasy'), ('romance', 'Romance'), ('sci-fi', 'Sci-Fi'), ('adventure', 'Adventure'), ('mecha', 'Mecha')], default='fantasy', help_text='Zadej žánr', max_length=20, verbose_name='Žánr')),
                ('rok_vydani', models.IntegerField(help_text='Zadej rok vydání knižní předlohy', verbose_name='Rok vydání')),
                ('hodnoceni', models.CharField(choices=[(1, 'VERY BAD'), (2, 'BAD'), (3, 'AVERAGE'), (4, 'GOOD'), (5, 'VERY GOOD')], default='1', help_text='Zadej hodnocení', max_length=1, verbose_name='Hodnocení')),
                ('studio', models.CharField(help_text='Zadej název studia', max_length=50, verbose_name='Studio')),
                ('ilustracni_foto', models.ImageField(blank=True, help_text='Nahrejte ilustrační foto', null=True, upload_to='ilustracni_foto', verbose_name='Ilustrační foto')),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animes',
                'ordering': ['titul'],
            },
        ),
        migrations.AlterField(
            model_name='knizni_predloha',
            name='titul',
            field=models.CharField(help_text='Zadej název knižní předlohy', max_length=100, verbose_name='Název'),
        ),
    ]
